# This file describes a conda environment that can be used by alpha testers
#
# Run the following command to set up this environment:
# $ conda env create -f test-environment.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f test-environment.yml
#
# Run the following command to activate the environment:
# $ source activate cubeviz-testing
#
# To deactivate the environment run the following command:
# $ source deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n cubeviz-testing

name: cubeviz-testing
channels:
  - glueviz/label/dev
dependencies:
  - python=3.6
  - pyqt
  - numpy>=1.13
  - scipy
  # This is necessary in some OSX environments to ensure that Python is
  # installed as a framework
  - matplotlib
  - glue-core>=0.12
  - glueviz
  - pip:
    - asteval
    - git+https://github.com/spacetelescope/specviz#egg=specviz
    - git+https://github.com/spacetelescope/cubeviz#egg=cubeviz
